name = "fe-news-worker"
main = "src/worker/index.js"
compatibility_date = "2024-01-01"

# 로컬 개발 설정
[dev]
port = 8787
local_protocol = "http"

# [vars]
# PRODUCTION_BASE_URL = "https://forhyundaisofteer.github.io/fe-news"

# 배포 설정
# [env.production]
# name = "fe-news-worker-prod"

